### ISSUE TITLE
simulation_parameters.properties

### ISSUE THREAD

**Issue by alexddd123** [alb1183/ML-RL-PureEdgeSim#4]
The following two configurations：
enable_registry=false
registry_mode=CLOUD
Hello author, I would like to ask about the role of these two parameter configurations.
I found the following code in the corresponding place:
protected void executeTaskOrDownloadContainer(FileTransferProgress transfer) { 
		if (SimulationParameters.ENABLE_REGISTRY && "CLOUD".equals(SimulationParameters.registry_mode)
				&& !((DataCenter) transfer.getTask().getVm().getHost().getDatacenter()).getType().equals(TYPES.CLOUD)) {
			// if the registry is enabled and the task is offloaded to the edge data centers
			// or the mist nodes (edge devices),
			// then download the container
			scheduleNow(this, DefaultNetworkModel.DOWNLOAD_CONTAINER, transfer.getTask());

		} else {// if the registry is disabled, execute directly the request, as it represents
				// the offloaded task in this case
			if (((DataCenter) transfer.getTask().getVm().getHost().getDatacenter()).getType().equals(TYPES.CLOUD))
				schedule(simulationManager, SimulationParameters.WAN_PROPAGATION_DELAY, SimulationManager.EXECUTE_TASK,
						transfer.getTask());
			else
				scheduleNow(simulationManager, SimulationManager.EXECUTE_TASK, transfer.getTask());
		}
	}
Is this a task caching-related measure?Does turning on or not opening have a substantial impact on the overall simulation?
I hope the author can help me with this confusion, I am very grateful

**Comment by alb1183** [comment]
This repository is a modified version of PureEdgeSim for a paper I published.

As I see your question is about the operation of PureEdgeSim rather than the implementation of my methods, I recommend you to go directly to the PureEdgeSim author's repository:
https://github.com/CharafeddineMechalikh/PureEdgeSim

**Comment by alexddd123** [comment]
Thank you for your patience and sharing. I have solved this problem.

**Comment by alexddd123** [comment]
I'd like to ask you a question: Do you still have a lot of hair? I don't mean to offend you. It's easy for programmers in China to lose their hair and become bald. I'm just joking. Please don't mind. But I'd also like to ask you: Did you graduate smoothly with your PhD? Everything is going well.
